### ISSUE TITLE
How make work MoneyInput.js in input type="number"

### ISSUE THREAD

**Issue by DenisAlliswell** [QuantumInformation/AngularDirectives#1]
Hi!

How can I use your directive with input type="number"? 

Now it works only for type="text"

**Comment by QuantumInformation** [comment]
Hi, what issue are you getting with  type number?



-- 

Kind regards
Nikos

**Comment by DenisAlliswell** [comment]
The input number resets when I'm typing more then 3 digits.

**Comment by QuantumInformation** [comment]
Hmm, it's cause the number inputs only take numbers and mine adds commas.
I'm not sure if it will be possible with type number.

-- 

Kind regards
Nikos

**Comment by DenisAlliswell** [comment]
Mm, I see. Well, ok)

**Comment by QuantumInformation** [comment]
Feel free to experiment )

On Wednesday, 22 July 2015, DenisAlliswell <notifications@github.com> wrote:

> Mm, I see. Well, ok)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QuantumInformation/AngularDirectives/issues/1#issuecomment-123611154>
> .
>


-- 

Kind regards
Nikos

**Comment by DenisAlliswell** [comment]
:+1:
